# -*- coding: utf-8 -*-
"""Matricula-posgrados-2022.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0A4IKVfiujfCp2b3ZtHzWZC0vKO39Fw

# Tabla de datos de registros de matricula en IES.

_Colombia 2022_

En el siguiente bloque de código se hace un llamado a la librería Pandas con la que se configuran y operan los dataframes.

## Importante

Antes de iniciar y correr el algoritmo, hay que ejecutar la primer línea de código que es la que realiza la conexión con Drives (Drives de Leonardo). Hay que confirmar si al darle ejecutar esta línea de código Google Colab _"activa"_ el Drive del usuario activo en el navegador. Si es otro usuario difernte al mio (Leonardo) puede que no encuentre el archivo y ocurra un error. Para que pueda encontrar el archivo base para operar cada usuario deberia contener en su Drive el mismo archivo, con el mismo nombre y en la misma ruta de acceso.
"""

from google.colab import drive
drive.mount('/content/drive')

# -------- Importando pandas ----------
import pandas as pd
df = pd.read_excel("/content/drive/MyDrive/Proyectos/Sebas/estudiantes_matriculados-2022_recurso.xlsx", sheet_name=["Matriculados E.S. 2022"], header=8)
print(df.keys()) # Crea un diccionario con solo una única llave - nombre de la pestaña
df_data = pd.DataFrame(df['Matriculados E.S. 2022']) # Creo un data frame con la información dentro del diccionario.
print(df_data.columns) # imprimo las columnas del data frame.

"""## Limitando el data frame

El data frame tiene muchas columnas que no son necesarias por ahora. Se crea un sub-dataframe que llamo _df_info_ del original que se llama _df_data_.


"""

df_info = df_data[['INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)',
                      'PROGRAMA ACADÉMICO',
                      'NIVEL ACADÉMICO',
                      'ÁREA DE CONOCIMIENTO',
                      'DEPARTAMENTO DE OFERTA DEL PROGRAMA',
                      'MUNICIPIO DE OFERTA DEL PROGRAMA',
                      'SEXO',
                      'SEMESTRE',
                      'MATRICULADOS']]
print(df_info.head())

"""## Limpiando los datos

Contando las lineas duplicadas y eliminandolas.
"""

print(f'Número de líneas duplicadas en df_info: {df_info.duplicated().sum()}')
print(f'Tamaño del dataframe df_info: {df_info.size}')
df_sin_duplicados = df_info.drop_duplicates()
print(f'Número de líneas duplicadas en df_sin_duplicados: {df_sin_duplicados.duplicated().sum()}')
print(f'Tamaño del dataframe df_sin_duplicados: {df_sin_duplicados.size}\n')
print("x -"*20)
print(f"\n Lista de columnas y tipos de datos: \n{df_sin_duplicados.dtypes}")

"""Generando lista de valores únicos por columnas para revisar nombres mal escritos. En este paso es mejor seleccionar las columnas que podemos intuir las respuestas."""

print(df_sin_duplicados['NIVEL ACADÉMICO'].unique()) # son pocos
print(df_sin_duplicados['SEXO'].unique()) # son pocos

# Pero podemos explorar los valores unicos sumando valores unicos por columna
nombres_unicos = [] # lista temporal para los nombres
valores_unicos = [] # lista temporal para el conteo de los valores únicos
lista_unicos = {}
for col in df_sin_duplicados.columns:
  nombres_unicos = df_sin_duplicados[col].unique()
  valores_unicos = len(nombres_unicos)
  lista_unicos[col] = valores_unicos
# --------- Importando pprint para imprimir bonito ---------
from pprint import pprint # para imprimir bonito las listas
print("\nLista de conteo de valores únicos por columnas\n")
pprint(lista_unicos)
print(type(lista_unicos))

"""## Resultado

En estos casos tenemos, por ejemplo 280 nombres únicos (diferentes) de Instituciones de Educación Superior, 1149 valores diferentes de números de matriculados, 393 nombres de municipios y 6192 nombres de programas académicos que hay que revisar para confirmar que esten bien escritos y que no esten generando un dato que no es correcto. Pero eso es mejor hacerlo más adelante.

## Líneas de estudio y análisis

```
Cortesía de Google Gemini.
Le pedí ayuda a la IA para que me diera algunas ideas de hacia donde dirigir el análisis.
```

## 📊 Análisis General de Demanda

Estas ideas te ayudarán a entender la distribución básica de la matrícula.

* **Top IES por Matrícula Total:** Identifica las **10 o 20 Instituciones de Educación Superior (IES)** con el mayor número de estudiantes matriculados. Esto te da una visión de las instituciones más grandes y demandadas a nivel nacional.
* **Distribución por Nivel Académico:** Analiza cómo se distribuye la matrícula entre los diferentes **'NIVELES ACADÉMICOS'** (e.g., pregrado, posgrado, técnico profesional, tecnológico). Esto revela dónde se concentra la mayor demanda educativa.
* **Distribución Geográfica:** Utiliza las columnas **'DEPARTAMENTO DE OFERTA DEL PROGRAMA'** y **'MUNICIPIO DE OFERTA DEL PROGRAMA'** para identificar las regiones (departamentos y ciudades) con la mayor concentración de estudiantes matriculados.

---

## 🔬 Análisis Específico de Programas y Áreas

Estas ideas se centran en los intereses académicos de los estudiantes.

* **Programas más Demandados:** Genera un *ranking* de los **'PROGRAMAS ACADÉMICOS'** individuales con mayor matrícula a nivel nacional o por departamento. ¿Cuáles son las carreras más populares?
* **Demanda por Área de Conocimiento:** Agrupa la matrícula por **'ÁREA DE CONOCIMIENTO'** (e.g., Ingeniería, Ciencias de la Salud, Ciencias Sociales). Esto te permite ver las grandes tendencias de demanda en el mercado laboral y académico.
* **Áreas de Crecimiento/Disminución (si tienes datos de semestres):** Si tu columna **'SEMESTRE'** permite diferenciar el primer y segundo semestre de 2022, puedes comparar la matrícula para ver qué áreas o programas tuvieron un cambio en la demanda en el transcurso del año.

---

## 👩‍🔬 Análisis Demográfico y de Equidad

Esta perspectiva te permite entender a quién está sirviendo el sistema.

* **Demanda por Sexo:** Compara la distribución de la matrícula según la columna **'SEXO'** (Hombres vs. Mujeres) a nivel total, por IES, o—lo que es más interesante—por **'ÁREA DE CONOCIMIENTO'** o **'PROGRAMA ACADÉMICO'**. Por ejemplo, ¿qué programas tienen una mayor desbalance de género?
* **Concentración en IES específicas:** Para programas o áreas muy demandadas, analiza la concentración; es decir, ¿cuántas IES cubren el 80% de la matrícula total de ese programa? Esto indica si la demanda está dispersa o si se concentra en unas pocas instituciones líderes.

---

## 🎯 Ideas Avanzadas para Visualización

* **Gráfico de Burbujas:** Crea un gráfico donde:
    * El **eje X** sea la Matrícula Total por IES.
    * El **eje Y** sea el Número de Programas Ofrecidos por IES (puedes calcular esto contando programas únicos por IES).
    * El **tamaño de la burbuja** represente la Matrícula promedio por Programa.
    * Esto te ayudará a diferenciar entre IES grandes con muchos programas ("generalistas") y IES especializadas con alta demanda en pocos programas ("nichos").
* **Mapa de Calor:** Utiliza un mapa de calor para cruzar las **'ÁREAS DE CONOCIMIENTO'** (filas) con los **'DEPARTAMENTOS'** (columnas). Los colores más intensos señalarán las áreas de mayor demanda en cada región.

## Forma de agrupar por una columna y sumar por otra

El dataframe reducido con el que se trabaja, tiene algunas columnas del dataframe original que debemos operar para iniciar los análisis.

El dataframe reducido contiene los siguientes _atributos_ (columnas):

- INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)    
- PROGRAMA ACADÉMICO                         
- NIVEL ACADÉMICO                            
- ÁREA DE CONOCIMIENTO                       
- DEPARTAMENTO DE OFERTA DEL PROGRAMA        
- MUNICIPIO DE OFERTA DEL PROGRAMA           
- SEXO                                       
- SEMESTRE                                   
- MATRICULADOS   

Para poder iniciar con el primer **Análisis General de Demanda** , se necesita agrupar todas los registros por el atributo **Institución de educación superior** y sumar sus **matrículados**.

Para agrupar y sumar los registros de un dataframe en Python, usa el método ._groupby()_ de Pandas, especificando la columna por la que deseas agrupar, y luego aplica el método _.sum()_ para obtener la suma de las columnas numéricas.

Por ejemplo:
```
df.groupby('columna_a_agrupar')['columna_a_sumar'].sum()
```

Para nuestro caso, el comandos se configura así:
```
df_sin_duplicados.groupby('INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)')['MATRICULADOS'].sum()
```

Probemos...
"""

# Separando por algunos departamentos del suroeste
valores_seleccionados=['Valle del Cauca','Cauca','Nariño','Huila'] # creando lista de separación
# creo un data frame hijo de un data frame padre que solo contiene la inforación de los departamentos seleccionados
df_suroeste = df_sin_duplicados[df_sin_duplicados['DEPARTAMENTO DE OFERTA DEL PROGRAMA'].isin(valores_seleccionados)]
# Creo una lista con los valores de las sumas de matrículas por IES
df_suma_matriculas_IES = df_suroeste.groupby('INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)')['MATRICULADOS'].sum()
# Veamos las 10 universidades con mayor número de matriculas en 2022.
print(df_suma_matriculas_IES.sort_values(ascending=False).head(20))
# el dataframe por ser dataframe tiene varias propiedades.
# Una es 'sort' que organiza la información, la otra es 'head' que selecciona los primeros datos.
print("\nSeparando solo la información de registro de matriculas de solo POSGRADOS\n")
# Separando por nivel académico [solo maestría]
df_so_maestria = df_suroeste[df_suroeste['NIVEL ACADÉMICO'].isin(['POSGRADO'])]
# Creo una lista con los valores de las sumas de matrículas por IES
df_suma_so_maestrias = df_so_maestria.groupby('INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)')['MATRICULADOS'].sum()
print(df_suma_so_maestrias.sort_values(ascending=False).head(20))

"""# _Gráficas_

## Análisis General de Demanda

Para lograr el **Análisis General de Demanda** voy a generar las gráficas propuestas punto por punto como propuso Gemini. A continuación preparo y organizo la información.
"""

# -------- Importando Matplotlib -----------------
import matplotlib.pyplot as plt # importando la librería para realizar las gráficas
# sort_values organiza | head toma los 20 primeros
lista_IES = df_suma_so_maestrias.sort_values(ascending=False).head(20)
# Separo los valores de la lista de nombres de las IES
nombres_IES = lista_IES.keys()
# print(nombres_IES) # prueba
valores_IES = lista_IES.values
# print(valores_IES) # prueba
# ******************************
# Creo objeto para crear gráfica
# ******************************
fig, ax =plt.subplots(figsize=(12, 6))# 12 inches wide, 6 inches tall
# configuración de los valores para el eje 'x' y el eje 'y', colores de las barras y grosor del delineado
hbars = ax.barh (nombres_IES, valores_IES, color='lightblue', edgecolor='black', linewidth=1.5, alpha=0.7)
# por alguna razón cambia el orden y hay que volver a cambiar el orden
ax.invert_yaxis()
# personalización de etiquetas, título, grilla y anotaciones
ax.set_xlabel('Matrículas', fontsize=16, color='grey') # detalles de etiqueta del eje 'x'
ax.set_ylabel('IES', fontsize=16, color='grey') # detalles de etiqueta del eje 'y'
ax.set_title('Lista de las 20 IES con mayores matrículas de Posgrado en Valle del Cauca, Cauca, Nariño, Huila - 2022',
             loc='right', color='grey', fontsize=20, pad=20) # detalles del título
ax.grid(axis='x', color='grey', linestyle='--', linewidth=0.5, alpha=0.2) # detalles de grilla
# configuración de anotaciones (valores al final de las barras)
ax.bar_label(hbars,labels=[f'{e}' for e in valores_IES], color='grey', padding=6, fontsize=6)
# Presentación del objeto
plt.show()

"""## Organizando data frames

Continuando con el **Análisis General de Demanda**, debo crear varios data frames agrupando por _NIVEL ACADÉMICO_, _DEPARTAMENTO DE OFERTA DEL PROGRAMA_ y _MUNICIPIO DE OFERTA DEL PROGRAMA_ para luego sumar el atributo _MATRÍCULA_.
"""

# filtremos el data frame para trabajar solo con los departamentos de
df_suma_nivel_academico = df_so_maestria.groupby('NIVEL ACADÉMICO')['MATRICULADOS'].sum()
df_suma_departamento_programa = df_so_maestria.groupby('DEPARTAMENTO DE OFERTA DEL PROGRAMA')['MATRICULADOS'].sum()
df_suma_municipio_programa = df_so_maestria.groupby('MUNICIPIO DE OFERTA DEL PROGRAMA')['MATRICULADOS'].sum()
print(f"\n __Imprimiendo el data frame suma por nivel académico:__ \n {df_suma_nivel_academico.head()}")
print(f"\n __Imprimiendo el data frame suma de departamentos:__ \n {df_suma_departamento_programa.head()}")
print(f"\n __Imprimiendo el data frame suma de municipios:__ \n {df_suma_municipio_programa.head()}")

"""**Nota**: El data frame de nivel académico solo contiene posgrados, por lo que se puede asumir que todos los matriculados del 2022 fueron un total de _37.996_ estudiantes en el nivel de **posgrados**.

Veamos como configuramos la gráfica para matriculados por departamento.
Pero, si quero ahorrar un poco de tiempo y pensandolo un poco, solo nesecito cambiar el data frame inicial, cambiar los nombre por unos mas adecuados, cuidar el _"domino de cambios"_ y tal vez, cambiar la forma de la gráfica a barras verticales.  
"""

# sort_values organiza | head toma los 20 primeros
lista_departamento_IES = df_suma_departamento_programa.sort_values(ascending=False).head(20) # DEPARTAMENTO DE OFERTA DEL PROGRAMA
# Separo los valores de la lista de nombres de las IES
departamentos_IES = lista_departamento_IES.keys()
# print(departamentos_IES) # prueba
valores_departamentos_IES = lista_departamento_IES.values
# print(valores_departamentos_IES) # prueba
# ******************************
# Creo objeto para crear gráfica
# ******************************
fig, ax =plt.subplots(figsize=(12, 3))# 12 inches wide, 3 inches tall
# configuración de los valores para el eje 'x' y el eje 'y', colores de las barras y grosor del delineado
hbars = ax.barh (departamentos_IES, valores_departamentos_IES, color='lightblue', edgecolor='black', linewidth=1.5, alpha=0.7)
# por alguna razón cambia el orden y hay que volver a cambiar el orden
ax.invert_yaxis()
# personalización de etiquetas, título, grilla y anotaciones
ax.set_xlabel('Matrículas', fontsize=16, color='grey') # detalles de etiqueta del eje 'x'
ax.set_ylabel('Departamentos', fontsize=16, color='grey') # detalles de etiqueta del eje 'y'
ax.set_title('Cantidad de matrículas de Posgrado en Valle del Cauca, Cauca, Nariño, Huila - 2022',
             loc='right', color='grey', fontsize=20, pad=20) # detalles del título
ax.grid(axis='x', color='grey', linestyle='--', linewidth=0.5, alpha=0.2) # detalles de grilla
# configuración de anotaciones (valores al final de las barras)
ax.bar_label(hbars,labels=[f'{e}' for e in valores_departamentos_IES], color='grey', padding=6, fontsize=6)
# Presentación del objeto
plt.show()

"""Ahora veamos como da la gráfica con los municipios"""

# sort_values organiza | head toma los 20 primeros
lista_municipios_IES = df_suma_municipio_programa.sort_values(ascending=False).head(20) # MUNICIPIO DE OFERTA DEL PROGRAMA
# Separo los valores de la lista de nombres de las IES
municipios_IES = lista_municipios_IES.keys()
# print(municipios_IES) # prueba
valores_municipios_IES = lista_municipios_IES.values
# print(valores_municipios_IES) # prueba
# ******************************
# Creo objeto para crear gráfica
# ******************************
fig, ax =plt.subplots(figsize=(12, 5))# 12 inches wide, 5 inches tall
# configuración de los valores para el eje 'x' y el eje 'y', colores de las barras y grosor del delineado
hbars = ax.barh (municipios_IES, valores_municipios_IES, color='lightblue', edgecolor='black', linewidth=1.5, alpha=0.7)
# por alguna razón cambia el orden y hay que volver a cambiar el orden
ax.invert_yaxis()
# personalización de etiquetas, título, grilla y anotaciones
ax.set_xlabel('Matrículas', fontsize=16, color='grey') # detalles de etiqueta del eje 'x'
ax.set_ylabel('Municipios', fontsize=16, color='grey') # detalles de etiqueta del eje 'y'
ax.set_title('Cantidad de matrículas de Posgrado en Valle del Cauca, Cauca, Nariño, Huila - 2022',
             loc='right', color='grey', fontsize=20, pad=20) # detalles del título
ax.grid(axis='x', color='grey', linestyle='--', linewidth=0.5, alpha=0.2) # detalles de grilla
# configuración de anotaciones (valores al final de las barras)
ax.bar_label(hbars,labels=[f'{e}' for e in valores_municipios_IES], color='grey', padding=6, fontsize=6)
# Presentación del objeto
plt.show()

"""## Propuesta para Refactorizar las gráficas

Al realizar las gráficas alcance a notar que solo es necesario cambiar algunas pocas cosas para repetir las gráficas.

- Obtener una lista con el dataframe agrupado (sea por nivel acadédico, departamento o municipio)
- Acomodar los nombres de las listas para que sean más coherentes los procesos internos (lista_municipios, valores_municipios | lista_departamentos, valores_departamentos).
- Títulos y etiquetas de las gráficas acordes a los datos a mostrar.

## Análisis especifico de programas y áreas

Siguiendo con el análisis, genero una lista de los programas académicos con mayores matrículas para la región sur oeste del paíz. Recordemos que el dataframe con estos datos es **df_so_maestria**.
"""

# Creo una lista con los valores de las sumas de matrículas por programa académico
df_sum_programa_academico = df_so_maestria.groupby('PROGRAMA ACADÉMICO')['MATRICULADOS'].sum() # PROGRAMA ACADÉMICO

df_programa_academico = df_sum_programa_academico.sort_values(ascending=False).head(20)
# print(df_programa_academico)
lista_programa_academico_IES = df_programa_academico.keys()
# print(lista_programa_academico_IES) # prueba
valores_programa_academico = df_programa_academico.values
# print(valores_programa_academico) # prueba
# ******************************
# Creo objeto para crear gráfica
# ******************************
fig, ax =plt.subplots(figsize=(12, 5))# 12 inches wide, 5 inches tall
# configuración de los valores para el eje 'x' y el eje 'y', colores de las barras y grosor del delineado
hbars = ax.barh (lista_programa_academico_IES, valores_programa_academico, color='lightblue', edgecolor='black', linewidth=1.5, alpha=0.7)
# por alguna razón cambia el orden y hay que volver a cambiar el orden
ax.invert_yaxis()
# personalización de etiquetas, título, grilla y anotaciones
ax.set_xlabel('Matrículas', fontsize=16, color='grey') # detalles de etiqueta del eje 'x'
ax.set_ylabel('Programas académicos', fontsize=16, color='grey') # detalles de etiqueta del eje 'y'
ax.set_title('Cantidad de matrículas de programas académicos en Valle del Cauca, Cauca, Nariño, Huila - 2022',
             loc='right', color='grey', fontsize=20, pad=20) # detalles del título
ax.grid(axis='x', color='grey', linestyle='--', linewidth=0.5, alpha=0.2) # detalles de grilla
# configuración de anotaciones (valores al final de las barras)
ax.bar_label(hbars,labels=[f'{e}' for e in valores_programa_academico], color='grey', padding=6, fontsize=6)
# Presentación del objeto
plt.show()

"""veamos por área de conocimiento"""

df_sum_area_de_conocimiento = df_so_maestria.groupby('ÁREA DE CONOCIMIENTO')['MATRICULADOS'].sum() # ÁREA DE CONOCIMIENTO

df_area_de_conocimiento = df_sum_area_de_conocimiento.sort_values(ascending=False).head(20)
# print(df_area_de_conocimiento)
lista_area_de_conocimiento = df_area_de_conocimiento.keys()
# print(lista_area_de_conocimiento) # prueba
valores_area_de_conocimiento = df_area_de_conocimiento.values
# print(valores_area_de_conocimiento) # prueba
# ******************************
# Creo objeto para crear gráfica
# ******************************
fig, ax =plt.subplots(figsize=(12, 5))# 12 inches wide, 5 inches tall
# configuración de los valores para el eje 'x' y el eje 'y', colores de las barras y grosor del delineado
hbars = ax.barh (lista_area_de_conocimiento, valores_area_de_conocimiento, color='lightblue', edgecolor='black', linewidth=1.5, alpha=0.7)
# por alguna razón cambia el orden y hay que volver a cambiar el orden
ax.invert_yaxis()
# personalización de etiquetas, título, grilla y anotaciones
ax.set_xlabel('Matrículas', fontsize=16, color='grey') # detalles de etiqueta del eje 'x'
ax.set_ylabel('Áreas de conocimiento', fontsize=16, color='grey') # detalles de etiqueta del eje 'y'
ax.set_title('Cantidad de matrículas por áreas de conocimiento en Valle del Cauca, Cauca, Nariño, Huila - 2022',
             loc='right', color='grey', fontsize=20, pad=20) # detalles del título
ax.grid(axis='x', color='grey', linestyle='--', linewidth=0.5, alpha=0.2) # detalles de grilla
# configuración de anotaciones (valores al final de las barras)
ax.bar_label(hbars,labels=[f'{e}' for e in valores_area_de_conocimiento], color='grey', padding=6, fontsize=6)
# Presentación del objeto
plt.show()

"""## Agrupando por semestre y programas

Para agrupar por dos criterios vamos a usar
"""

df_sum_area_de_conocimiento_y_semestre = df_so_maestria.groupby(['SEMESTRE','ÁREA DE CONOCIMIENTO'])['MATRICULADOS'].sum() # SEMESTRE y ÁREA DE CONOCIMIENTO
print(df_sum_area_de_conocimiento_y_semestre.head())

"""### Usando `pprint` para el diccionario `df_sum_area_de_conocimiento_y_semestre`

`pprint` es ideal para imprimir diccionarios y listas de manera legible, mostrando su estructura anidada.
"""

from pprint import pprint

print("Estructura del diccionario `df_sum_area_de_conocimiento_y_semestre`:")
pprint(df_sum_area_de_conocimiento_y_semestre)

"""### Usando `df.info()` y `df.dtypes` para el DataFrame `df_sin_duplicados`

Para DataFrames, `info()` te dará un resumen conciso de todas las columnas, sus tipos de datos no nulos y el uso de memoria, mientras que `dtypes` solo te mostrará los tipos de datos.
"""

print("Estructura e información del DataFrame `df_sin_duplicados` usando `info()`:")
df_sin_duplicados.info()

print("\nTipos de datos del DataFrame `df_sin_duplicados` usando `dtypes`:")
print(df_sin_duplicados.dtypes)

"""Si estás buscando visualizar la estructura de un objeto de Python más genérico (no necesariamente un diccionario o un DataFrame), o si tienes un objeto personalizado y quieres ver sus atributos de forma jerárquica, por favor házmelo saber y puedo crear una función personalizada para eso."""